### ISSUE TITLE
KB-COMMENT-47: Section 9

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#134]
KB:

We should probably have some discussion of the consequences of
compromise of the server's cookie-encryption key.  Possibly also for
when the key associated with a cookie is compromised from a client,
though if cookies are single-use the scope may be quite limited.  (That
is, since we are using the shared symmetric key for authentication by
virtue of "I didn't send it so it must be from the other party that has
the key".)

**Comment by dansarie** [comment]
Here's a reply I made on the list to a similar question earlier today:
> NTP and NTS-KE server
> operators are expected to remove compromised keys as soon as the
> compromise is discovered. This would cause the NTP servers to respond
> with NTS NAK, thus forcing key renegotiation. I am aware that this does
> not protect against MITM attacks where the attacker has access to a
> compromised cookie encryption key.

Also, clients whose keys have been compromised can (and should) perform a new NTS key exchange.

**Comment by dsibold** [comment]
Agree

**Comment by ragges** [comment]
Agree. I suppose he wants it in the draft, too.

**Comment by dansarie** [comment]
I see no reason for changing the draft.

**Comment by KTeichel** [comment]
I agree with Marcus in that I don't see how adding something to the draft would be beneficial.
If client keys are compromised, the client has a clear way forward and no-one else is affected.

If server keys are compromised, there might be some benefit to notifying people, but the server must by our specification be unaware of who those people are, so... nothing to be done other than key rollover I guess?

**Comment by ragges** [comment]
Agree, no change
