### ISSUE TITLE
KB-COMMENT-22: Section 4.1.7, 4 - revisited

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#163]
New comment from Benjamin 2020-03-19:

> I think that was clear.  The argument (IIRC) I refer to is basically that
> the protocol-level difference between going from "foo/1" to "foo/2" and
> going from "foo" to "foov2" is negligible, and in the latter case you get
> prettier identifiers for the initial batch of time.
> 

Old issue: #109

**Comment by ragges** [comment]
It seems the not-/N style, that Benjamin proposes, is what is mainly used today.
I am ok with a change.

**Comment by ragges** [comment]
NOTE - the second patch includes an incorrectly correct extra space - it is needed for the table for the IANA application.

**Comment by ragges** [comment]
NOTE - we also apply for the "TLS Application-Layer Protocol Negotiation (ALPN) Protocol IDs registry" entry:
ntske/1
Should we remote the /1 there too? Here is the registry today:
[https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids)

**Comment by KTeichel** [comment]
I have no strong opinion on this either way.

**Comment by dansarie** [comment]
@ragges: the space you removed in db02aa4 is there to ensure proper line breaking in the table in section 7.3.

This change will break compatibility with existing implementations, though that may be a feature...

As for removing the /1 from the ALPN registry entry, I'm opposed. It appears to be more or less the standard to include the version number there, thus enabling protocol version negotiation.

**Comment by ragges** [comment]
(I understood that later, that is why I put it back in the next commit.)

**Comment by dansarie** [comment]
Oh. I missed that. Sorry.
