### ISSUE TITLE
KB-COMMENT-47: Section 9 - revisited

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#165]
New comment from Benjamin 2020-03-19:

> > > Section 9
> > > 
> > > We should probably have some discussion of the consequences of
> > > compromise of the server's cookie-encryption key.  Possibly also for
> > > when the key associated with a cookie is compromised from a client,
> > > though if cookies are single-use the scope may be quite limited.  (That
> > > is, since we are using the shared symmetric key for authentication by
> > > virtue of "I didn't send it so it must be from the other party that has
> > > the key".)
> > > 
> > 
> > NTP and NTS-KE server operators are expected to remove compromised keys as soon
> > as the compromise is discovered. This would cause the NTP servers to respond
> > with NTS NAK, thus forcing key renegotiation. We are aware that this does
> > not protect against MITM attacks where the attacker has access to a
> > compromised cookie encryption key.
> > 
> 
> I did not doubt that you are aware of this; the question is whether all
> future readers of this document will similarly be aware.
> 

Old issue: #134

**Comment by ragges** [comment]
Change proposal pushed (in separate branch this time).

**Comment by KTeichel** [comment]
Tiny nit: capitalisation in headline is inconsistent with rest of document (should be "Key Compromise" instead of "Key compromise").

**Comment by ragges** [comment]
Good catch, thanks!

**Comment by dansarie** [comment]
To fix a couple of nits, I propose a slightly different text:
> If the suggested format for NTS cookies in <xref target="suggested-format-for-nts-cookies"/> of this draft is used, an attacker who has gained access to the secret cookie encryption key `K` can impersonate the NTP server, including generating new cookies. NTP and NTS-KE server operators SHOULD remove compromised keys as soon as the compromise is discovered. This will cause the NTP servers to respond with NTS NAK, thus forcing key renegotiation. Note that this measure does not protect against MITM attacks where the attacker has access to a compromised cookie encryption key. If another cookie scheme is used, there are likely similar considerations for that particular scheme.

**Comment by ragges** [comment]
Fine, new commit pushed.
(I really like the graphical diff that you get!)

**Comment by dansarie** [comment]
I see now that the XML tag was stripped from my previous reply. New attempt:
```
If the suggested format for NTS cookies in
<xref target="suggested-format-for-nts-cookies"/> of this draft is used, an
attacker who has gained access to the secret cookie encryption key `K` can
impersonate the NTP server, including generating new cookies. NTP and NTS-KE
server operators SHOULD remove compromised keys as soon as the compromise is
discovered. This will cause the NTP servers to respond with NTS NAK, thus
forcing key renegotiation. Note that this measure does not protect against MITM
attacks where the attacker has access to a compromised cookie encryption key.
If another cookie scheme is used, there are likely similar considerations for
that particular scheme.
```

**Comment by ragges** [comment]
No, the xref is there, but in not in the slash-greated-than format. There is some other problem. I haven't dared to use that kind of xrefs since I have no control over the result from the XML converter thing.
