### ISSUE TITLE
KB-COMMENT-53: Section 9.7 - revisited - part 1

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#166]
New comment from Benjamin 2020-03-19:

> > > Is there anything to say about a target end-state where some peers can
> > > successfully require NTS for all connections (i.e., no fallback of any
> > > sort)?
> > > 
> 
> (I'll take that as a "no".)

Old issue: #140

**Comment by ragges** [comment]
NOTE - I had by mistake grouped those two questions in one issue, so we did not answer.

**Comment by dansarie** [comment]
I think this will be handled by the ongoing work on NTS service discovery etc. in the WG.

**Comment by ragges** [comment]
I agree!

**Comment by ragges** [comment]
Proposed reply:
We believe that this will be handled by the ongoing work on NTS service discovery etc. in the WG. In addition, it is a question about implementation and application.

**Comment by dansarie** [comment]
:+1: (i.e. agree!)

**Comment by dsibold** [comment]
Agree

**Comment by KTeichel** [comment]
Agree with the reply and the "no change" decision.
