### ISSUE TITLE
KB-COMMENT-53: Section 9.7 - revisited - part 2

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#167]
New comment from Benjamin 2020-03-19:

> > > For the reasons described here, implementations SHOULD NOT revert
> > > from NTS-protected to unprotected NTP with any server without
> > > explicit user action.
> > > 
> > > Which would then force a choice between tolerating bad time and reusing
> > > cookies, until user action can be obtained?
> > > 
> > 
> > This is about not accepting a downgrade from NTS-protected to
> > unprotected (traditional) NTP. Whether cookies are reused or not is
> > another issue, and is only about unlinkability of the client vs
> > resilience of the time link.
> 
> If there's an attacker stripping NTS so I get unprotected responses, I'll
> quickly use up my cookie pool since there's no NTS return traffic to
> replenish it.  I could try NTS-KE again, though maybe the attacker can
> block that as well.  With no cookie pool, I either have no time service at
> all, an insecure time service, or a secure time service with cookie reuse.
> I expect most people to choose the last one, but perhaps in some cases the
> first one would be preferred.

Old issue: #140

**Comment by ragges** [comment]
It seems that we have forgotten to specify that a client must not accept unprotect NTP responses to a protected request!

**Comment by KTeichel** [comment]
I agree with this reply.
I also agree with the implied "no change to the document" (although I also wouldn't oppose an appropriate paragraph at this point, since several reviewers seem to have stumbled over this).

**Comment by ragges** [comment]
Right! As you probably understood, I initially didn't find where this was specified either, and thought we have missed it. Also, the 9.6 ("Security Considerations", "NTS Stripping") is a little bit misleading here, it seems to be a risk. It could be more explicit both in 5.7 and 9.6.

**Comment by ragges** [comment]
I have pushed two minor suggestions to changes, one for 5.7 and one for 9.6, that I think will improve the situation.

**Comment by dansarie** [comment]
I advocate no change:

Section 5.7 already says this:
> The client MAY reuse cookies in order to prioritize resilience over
> unlinkability.  Which of the two that should be prioritized in any
> particular case is dependent on the application and the user's
> preference.  Section 10.1 describes the privacy considerations of
> this in further detail.

**Comment by ragges** [comment]
I do not think that that text says this - this is about that some reviewers have not understood that:
          This means that a client will only accept an NTS-protected response to
           an NTS-protected request.

**Comment by dansarie** [comment]
101e7a5 really shouldn't be necessary.

670e04b is a good fix, though "attempts to trick" would be even better.

**Comment by ragges** [comment]
Yes, that is better, changed.

**Comment by ragges** [comment]
I agree that the first one not should be necessary, but it seems several people misunderstand this, and when I searched for it, I first couldn't find it (since it is somewhat hidden in that paragraph in 5.7).
Other suggestions on how to make this more explicit are welcome!

**Comment by dansarie** [comment]
New suggestion:
> The client MUST NOT accept unprotected responses to NTS-protected requests. In
> particular, upon receiving an NTS-protected response, the client MUST verify
> that the Unique Identifier matches that of an outstanding request, and that the
> packet is authentic under the S2C key associated with that request. If either
> of these checks fails, the packet MUST be discarded without further processing.
