### ISSUE TITLE
KB-DISCUSS-1 revisited

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#172]
BK:
> > > I'm happy to see prominent references to RFCs 7525 and 6125.
> > > Unfortunately, merely citing RFC 6125 does not provide a usable
> > > specification for an application to implement; we need to additionally
> > > state what type of name (e.g., SRV-ID or DNS-ID) is used as input to the
> > > validation process and how the application obtains that name.  Given
> > > that we are defining a service name (and port number) for ntske, SRV-ID
> > > might be appropriate (DNS-ID is the most common form I see consumers
> > > of RFC 6125 using).
> > 
> > The service discovery is not in scope for this draft, and we anticipate
> > several different methods in the future. There are already discussions
> > going on on the ntp working group. We therefore do not specify these things
> > here, but want to refer to the relevant specifications for the different
> > methods. The rules for constructing a list of reference identifiers for
> > certificate validation is laid out in Section 6.2.1. of RFC 6125. This is what
> > we expect NTS-KE clients to do.
> 
> I don't think it's appropriate to leave the selection of type of identifier
> fully up to the application; even if we don't discuss server discovery, we
> can still discuss the framework used for naming servers, as naming is a key
> part of authentication and authorization.  RFC 6125 itself acknowledges
> this, noting in Section 2.1 that:
> 

> >   [...] Ideally, protocol specifications that
> >   reference this document will specify which identifiers are mandatory-
> >   to-implement by servers and clients, which identifiers ought to be
> >   supported by certificate issuers, and which identifiers ought to be
> >   requested by application service providers.  Because these
> >   requirements differ across applications, it is impossible to
> >   categorically stipulate universal rules (e.g., that all software
> >   implementations, service providers, and certification authorities for
> >   all application protocols need to use or support DNS-IDs as a
> >   baseline for the purpose of interoperability).
> > 
> >   However, it is preferable that each application protocol will at
> >   least define a baseline that applies to the community of software
> >   developers, application service providers, and CAs actively using or
> >   supporting that technology (one such community, the CA/Browser Forum,
> >   has codified such a baseline for "Extended Validation Certificates"
> >   in [EV-CERTS]).
> 

> 
> The checklist in Section 3 also gives guidance to application protocol
> designers as to how to select the type of identifier to be used for their
> protocol.
>

**Comment by ragges** [comment]
I think we need to better understand the issue, mail to B sent, no reply yet.

**Comment by dansarie** [comment]
Best would be if Benjamin could provide a text suggestion.

**Comment by ragges** [comment]
Agreed, that would be best!

**Comment by ragges** [comment]
We haven't heard from B. We can maybe do some minimalist thing according to the references he gave, and hope that is enough. I'll look into it.

**Comment by dsibold** [comment]
Ragges, I liked to last email you did sent to Ben. I would propose to add this question in the overall answer to his discussion point again.

**Comment by ragges** [comment]
@dsibold - Right, will do!

**Comment by KTeichel** [comment]
That seems like a good way forward.

**Comment by ragges** [comment]
All, I has pushed a commit with something to use if B does not respond shortly.
Please check it out and see if you can live with it.
<https://github.com/ragges/nts/commit/7b219e2f4485ae3b9e04b7d50b40dcd1e619691e>

If you agree to it, I believe we could use this and push a new draft and answer the reviewers now, and if B says there is some problem, we could fix just that.

**Comment by dansarie** [comment]
Here's my opinion:
Section 1.2 of RFC 6125 says:
> The primary audience for this document consists of application
> protocol designers, who can reference this document instead of
> defining their own rules for the representation and verification of
> application service identity.

In other words, RFC 6125 explicitly states that it exists so that we don't have to specify all this in our draft.

That said, a more prominent reference to RFC 6125 in Section 3 would not be bad. I suggest:
> Implementations MUST follow the rules in RFC 5280 and RFC 6125 for the representation and verification of application service identity. Use of the DNS-ID identifier type is RECOMMENDED. Section 9.4 of this memo discusses particular considerations for certificate verification in the context of NTS.

**Comment by ragges** [comment]
Ok, I am fine with Marcus' suggestion.
Should we add some room for  later versions about those documents, or is that implied?
I now realise that I forgot to explain/reference "DNS-ID", we should add that (just point to 6125, I think).

**Comment by dsibold** [comment]
I'm also fine with Marcus's proposal. 
Yes, a reference to 6125 for DNS-ID would be worthwhile.

**Comment by dsibold** [comment]
I would think pushing a new version of the draft and sending the answer to the reviews as Ragnar proposed should be the next steps. Great work.

**Comment by ragges** [comment]
Thank you too!

I don’t really expect a reply from Ben, so I think so too.

After all, if he would object to that 6125 DNS-ID thing, we could quickly make a new version.

I have started to prepare a new email reply to him, and also “release notes” for the new draft.
(here: <https://github.com/ragges/nts-responses/>)

Have a nice evening!

/ragge

**Comment by dansarie** [comment]
Fixed in e376973.
