### ISSUE TITLE
KB-DISCUSS-1 take 3

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#178]
KB:

> It does suffice to clear the Discuss, though if I may suggest
> 
> OLD:
> >   Implementations MUST follow the rules in RFC 5280 [RFC5280] and RFC
> >   6125 [RFC6125] for the representation and verification of application
> >   service identity.  Use of the DNS-ID identifier type [RFC6125] is
> >   RECOMMENDED.  Section 9.5 of this memo discusses particular
> >   considerations for certificate verification in the context of NTS.
> 
> 
> NEW:
> >   Implementations MUST follow the rules in RFC 5280 [RFC5280] and RFC 6125
> >   [RFC6125] for the representation and verification of the application's
> >   service identity.  When NTS-KE service discovery (out of scope for this
> >   document) produces one or more host names, use of the DNS-ID identifier
> >   type [RFC6125] is RECOMMENDED; specifications for service discovery
> >   mechanisms can provide additional guidance for certificate validation
> >   based on the results of discovery.  Section 9.5 of this memo discusses
> >   particular considerations for certificate verification in the context of
> >   NTS.
> 
> 
> In particular, I don't want us to diverge from the RFC 6125 recommendation
> to encourage SRV-ID when DNS SRV records are used in discovery.
>

**Comment by ragges** [comment]
I am fine with this change. Proposed patch above.

**Comment by dansarie** [comment]
I am also perfectly fine with the change. However, I don't understand the motivation:
> In particular, I don't want us to diverge from the RFC 6125 recommendation
> to encourage SRV-ID when DNS SRV records are used in discovery.

Aren't we encouraging DNS-ID when DNS SRV records are used in discovery, or am I reading it wrong?

**Comment by ragges** [comment]
I read it as:
For SRV records, we (really) should do some SRV-ID thing, and not something else.
My notes: I agree, and preferably in some of the standard ways of doing it regarding on how the DNS names are made.

**Comment by dansarie** [comment]
But the proposed text says:
> When NTS-KE service discovery (out of scope for this
document) produces one or more host names, use of the DNS-ID identifier
type [RFC6125] is RECOMMENDED; specifications for service discovery
mechanisms can provide additional guidance for certificate validation
based on the results of discovery.

I am reading the first part of that sentence as "DNS-ID SHOULD be used for host names the client got through service discovery."

**Comment by KTeichel** [comment]
I too am fine with the change.

**Comment by ragges** [comment]
@dansarie
At least the first part doesn't really go with the comment below, really.

I do think though, that this would apply if one uses e.g. multiple A/AAAA records to resolve one name to multiple servers (DNS round-robin) (like pool does) - then those servers should all have the DNS-ID if the record that was looked up (e.g.: ntsntp.example.com points to more than on KE server, then all the certificates should have "ntsntp.example.com" their subjectAltNames.).

There is an alternative to A/AAAA round-robin here, that they open for in some specs but I don't recall which ones from the top of my head; if part of the lookup process is protected by other means, such as DNSSEC, the name in the certificate does not have to be the same as the user originally said/configured.

The second part, "specifications for service discovery mechanisms can provide additional guidance for certificate validation based on the results of discovery.", maybe goes with the comment, but not very explicitly.

**Comment by dansarie** [comment]
Sorry for not doing this yesterday.
