### ISSUE TITLE
HM - cookie placeholder, simplification for implementations

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#180]
On Thu, Jan 30, 2020 at 06:04:08PM -0800, HM wrote:

> Would it be cleaner in the long run to pick one?  The idea is to simplify 
> things so they are more likely to work and simpler to test.
> 
> Yes, I think it would make things simpler if the draft said that the
> placeholder SHOULD NOT be encrypted and MAY be ignored by the server
> if encrypted. I don't see a point in encrypting this field.
> 
> The same may apply to future extension fields.
>

**Comment by ragges** [comment]
Happened to see this, by accident. It seems several of the implementors wants this.
Should be a small change:
OLD:
   The client MAY include one or more NTS Cookie Placeholder extension
   fields which MUST be authenticated and **MAY** be encrypted.  The number
NEW:
   The client MAY include one or more NTS Cookie Placeholder extension
   fields which MUST be authenticated and **MUST NOT** be encrypted.  The number

**Comment by ragges** [comment]
On the other hand, if someone decides to use it for data transfer in the future as B suggested, they may want it to be encrypted...

**Comment by dansarie** [comment]
In any case, its too late for technical changes to the draft at this point, unless they are really, really necessary.

**Comment by ragges** [comment]
Ok, fine!

**Comment by ragges** [comment]
I suggest to close this case.
