### ISSUE TITLE
SM-D-2: Section 4, p 8

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#34]
SM:

>    in the TLS-protected channel.  Then, the server SHALL send a single
>    response 
> and
>    The client's request and the server's response
> but 
>                                                     Requests and
>    non-error responses each SHALL include exactly one NTS Next Protocol
>    Negotiation record.
> 

Is there a single request and single response, or plural requests
and responses?  If there are many, do they have to have the same
Next Protocol?

**Comment by dsibold** [comment]
The the change in the fix

**Comment by ragges** [comment]
Dieter spotted a typo in first fix, fixed in fix version 2.

**Comment by dansarie** [comment]
Do not agree. The text is fine as it is. The plural form does not indicate that multiple requests or responses are allowed, but that the SHALL requirement applies to requests and responses in general.

**Comment by ragges** [comment]
Ok - I am fine with that interpretation too.
