### ISSUE TITLE
SM-D-3: Section 4, page 9

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#35]
SM:

>       unrecognized Record Type MUST ignore the record if the Critical
>       Bit is 0 and MUST treat it as an error if the Critical Bit is 1.

If it is an error, what then?  The server can reply with an Error record
type, if so, what would the code be?  What would the client do?

**Comment by dsibold** [comment]
OK

**Comment by dansarie** [comment]
The fix does not address the question "What would the client do [when it receives a Unrecognized Critical Record message]?" My feeling is that this is implementation dependent and not something we should specify here. Reasonably though, the client should not continue trying.

**Comment by ragges** [comment]
Right. There are more of those, "what should X do on event Y". I too think it is likely implementation dependent. It may also be fine to try again in, say, 24 hours - if e.g. the server misbehaves, perhaps after an upgrade, it is quite likely to be fixed sooner or later.

**Comment by ragges** [comment]
So - do we agree on no change, and the reply "implementation dependant"?

**Comment by dansarie** [comment]
I guess so. Marking with "consensus".
