### ISSUE TITLE
SM-D-4: Section 4, page 9

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#36]
SM:
>   significant bit of the first octet.  In C, given a network buffer

There is a bit called "C" discussed on this page, took me aback a bit.
Probably not a problem, but if there's an opportunity to say "In the C 
language", maybe you should.

**Comment by dsibold** [comment]
OK with me

**Comment by dansarie** [comment]
I suggest "in the C programming language", which is the name of the language (and the book).

**Comment by KTeichel** [comment]
Sounds good to me.
