### ISSUE TITLE
SM-D-11: Section 4.1.5, page 12, 1

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#43]
SM:
> It is
>  empty if the server supports none of the algorithms offered.

If it is empty, what does the client do?  retry with a new request?
(yadayada about whether the Section 4 intro page 8 means that can't be)
or declare failure and communicate with the NTP server without NTS protections?  should the server send the TLS "Close notify" alert
after sending the empty algorithms list?

**Comment by ragges** [comment]
Dieter previously:
- I would argue that this should not be specified by the protocol.
- The server will send a TLS "Close notify" anyway. Because of the empty record
the client will not be able to establish a NTS protected association with the
server. In this case the client is responsible how to proceed. Either 
retry the whole procedure with a different AEAD algorithm (if it is able to), or 
proceed with unprotected plain NTP packets, or giving up and trying a different
NTP server.  We do think that this should not be specified in the protocol.

**Comment by dansarie** [comment]
Agree.
