### ISSUE TITLE
SM-D-12: Section 4.1.5, page 12, 2

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#44]
SM:
>  Server implementations of NTS extension fields for NTPv4 (Section 5)
>  MUST support AEAD_AES_SIV_CMAC_256

Does this apply to the client as well?  If so, is it advisable for
the client to always include that algorithm?  Is it mandatory for the
client to include that algorithm?

**Comment by ragges** [comment]
This does not apply to the client.

**Comment by dsibold** [comment]
Agree.

**Comment by dansarie** [comment]
Agree.
