### ISSUE TITLE
SM-D-13: Section 4.1.6 page 13

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#45]
SM:
>  Clients MUST NOT send records of this type.

What does the server do if the client does?  Send an Error and if
so with what code?

**Comment by ragges** [comment]
I believe this is now handled by the same fix as for SM-D-8, a more explicit definition of Error code 1/"Bad Request" in section 4.1.3.

**Comment by dansarie** [comment]
Agree.

For reference, SM-D-8 is #40 and the fix is b788fe3.

**Comment by dansarie** [comment]
Fixed by b788fe3.
