### ISSUE TITLE
SM-D-31: Appendix A

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#63]
SM:
(I wasn't going to note this nit, but since you have a list...)

NTS NAK should be on this list.

Actually, NTS NAK is not defined before it is used.  In Section 5.7, page 23
it says "NTS negative-acknowledgment (NAK)" but it does not say
"NTS NAK".  So a search for the acronym does not find its definition.

**Comment by dsibold** [comment]
Acknowledged.

**Comment by dansarie** [comment]
Ok.
