### ISSUE TITLE
SM-D-24: Section 6 page 24, 1B

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#74]
>  This section is non-normative.  It gives a suggested way for servers
>  to construct NTS cookies.  
and manage the server (NTS-KE and NTP) keys
>
>  Servers should select an AEAD algorithm which they will use to
>  encrypt and authenticate cookies.

NTS-KE encrypt cookies with this algorithm, NTP servers authenticate 
cookies with this algorithm, so in this case "servers" means both of 
them, right?
And both must make the same choice, right?
(And this is one of the places where it really sounds like you mean 
MUST or SHALL.)

**Comment by ragges** [comment]
Yes, the KE server and the NTP server need to agree on cookie formats, algorithms and keys for that particular implementation to work. This is still non-normative, not sure if we should require anything really.

**Comment by dsibold** [comment]
I tend to leave it as it is.

**Comment by dansarie** [comment]
Agree.
